version: '3.8'

services:
    app:
      build:
        context: ./
        dockerfile: ./Dockerfile
      container_name: daily-diet-api
      ports:
        - 3001:3001
        - 5555:5555
      volumes:
        - .:/usr/app
    db:
      container_name: postgres
      image: postgres:alpine
      restart: always
      environment:
        - POSTGRES_USER=pguser
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=db_development
      ports:
        - 5432:5432
    